
add_library(DYVGenTL SHARED IMPORTED)
set(DYVGenTL_DIR ${CMAKE_CURRENT_LIST_DIR}/../SDKlib)
if(WIN32)
set_property(TARGET DYVGenTL PROPERTY IMPORTED_LOCATION ${DYVGenTL_DIR}/DYVGenTL.cti)
set_property(TARGET DYVGenTL PROPERTY IMPORTED_IMPLIB ${DYVGenTL_DIR}/DYVGenTL.lib)
else()
set_property(TARGET DYVGenTL PROPERTY IMPORTED_LOCATION ${DYVGenTL_DIR}/libDYVGenTL.cti)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/Vidu_SDK_Api.cmake")
